name: CD Pipeline

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: AWS EC2 pull docker image from docker hub
        run: sudo docker pull liow/gitaction:latest

      - name: Delete old docker container
        run: sudo docker rm -f gitaction || true

      - name: Run docker container
        run: sudo docker run -d -p 8080:80 --name gitaction-container liow/gitaction
